services:
  node1:
    hostname: node1
    networks:
      - blockchain
    image: relfick/sharp-chain
    environment:
      NODE_ADDRESS: node1
      PEER_ADDRESSES: node2,node3
    depends_on:
      - node2
      - node3
  node2:
    hostname: node2
    networks:
      - blockchain
    image: relfick/sharp-chain
    environment:
      NODE_ADDRESS: node2
      PEER_ADDRESSES: node1,node3
  node3:
    hostname: node3
    networks:
      - blockchain
    image: relfick/sharp-chain
    environment:
      NODE_ADDRESS: node3
      PEER_ADDRESSES: node2,node1

networks:
  blockchain: